package com.alsutton.parser;

/**
 * Interface for classes wishing to listen to events generated by the parser.
 */

import java.util.*;

public interface EventListener
{
  public void plaintextEncountered( String text );
}
